### ISSUE TITLE
Request to Add Option for Displaying Full 'SHA' Field

### ISSUE THREAD

**Issue by nurlanmamedov** [liuliu-dev/CommitGraph#109]
Hi,

Thank you for the great plugin!

I noticed that the 'sha' field is automatically truncated to a maximum length of 7 characters. I would like to have the option to display the full 'sha' field value.

Is it possible to add a property that allows showing the full 'sha'?

I am willing to help refactor and improve this feature.

Thank you!

<img width="1018" alt="Screenshot 2024-06-13 at 00 34 54" src="https://github.com/liuliu-dev/CommitGraph/assets/36840386/b0518acf-5e94-4daa-88b8-1f5890083b87">

**Comment by liuliu-dev** [comment]
Hi @nurlanmamedov , I just added the support for full sha, set `fullSha` to be true to enable it.

**Comment by nurlanmamedov** [comment]
Thanks 👍
