### ISSUE TITLE
onClick listener

### ISSUE THREAD

**Issue by inverted-capital** [liuliu-dev/CommitGraph#196]
Thank you for this component - it is a great upgrade from the other outdated options.

Could you please give us some hints how to implement an onclick listener elegantly in your codebase ?  Any time the user touches or clicks on a commit, we want to receive a notification so we can react accordingly in other areas of our application.

**Comment by inverted-capital** [comment]
If we could maybe get an onClick prop to the `CommitGraph` components, that gets called with the current commit and current branch perhaps ?

**Comment by inverted-capital** [comment]
Be nice to have a selection array passed in to the CommitGraph component too, so we can highlight selected commits.  I will attempt a PR at this.

**Comment by liuliu-dev** [comment]
Thanks for your input. In version 2.2.7, I've added an optional `onCommitClick` prop for custom click actions.  I've also added a feature that changes the background color of a clicked commit.

I've decided against including the selected array feature within the component, you can manage this state externally as needed.

I'll be closing the related PRs and this issue. I appreciate your understanding.

**Comment by inverted-capital** [comment]
Thank you kindly!
