### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by nurlanmamedov** [liuliu-dev/CommitGraph#93]
Hello,

Thank you for the great plugin! I tested your examples in StoryBook and installed it locally. However, I encountered a problem in React.

Every time I use the component, the following warning appears:

```
Warning: Each child in a list should have a unique "key" prop.
```

Steps to reproduce:

    Install the plugin locally.
    Use the component in a React application.
    Open the browser console and see the warning.

Expected behavior:
    There should be no warnings in the console.

Additional information:
    It would be great if you could add unique keys for each list item.

I have attached a screenshot of the problem:

<img width="1511" alt="Screenshot 2024-05-29 at 22 44 38" src="https://github.com/liuliu-dev/CommitGraph/assets/36840386/ab1b96f4-25ed-4672-9e90-f21d58016513">

Thank you!

**Comment by liuliu-dev** [comment]
Hi @nurlanmamedov , thanks for the issue!
I just merged a fix, the warning should be gone now.
Let me know if you run into any issues 🙂

**Comment by nurlanmamedov** [comment]
> Hi @nurlanmamedov , thanks for the issue! I just merged a fix, the warning should be gone now. Let me know if you run into any issues 🙂

Cool, thanks 🙂
