### ISSUE TITLE
commitDate customisation

### ISSUE THREAD

**Issue by vugardadalov** [liuliu-dev/CommitGraph#94]
Hi: 
I saw you are parsing `commitDate` in [`CommitDetails:21`](https://github.com/liuliu-dev/CommitGraph/blob/fc4f2295bc1f305b7ea6bf1727008f32459be49d/src/components/CommitDetails/index.tsx#L21) component.  

```js
const date = commit.commitDate.toLocaleDateString();
```

I would like  to add custom date format or relative time. 
Is it possible to add a prop like `displayCommitDate?: string;` to show instead of `commitDate`?
```js
export type CommitNode = {
  .....
  commitDate: Date;
  displayCommitDate?: string;
  ....
};
```

**Comment by liuliu-dev** [comment]
Hey @vugardadalov , I added an optional date format function `dateFormatFn`:

```ts
dateFormatFn?: (d: string | number | Date) => string;
```

You can pass it to the component like this:

```ts
    <CommitGraph.WithInfiniteScroll
      commits={commits}
      loadMore={loadMore}
      hasMore={hasMore}
      branchHeads={branches}
      dateFormatFn={customDateTimeFormatFn}
    />
```

Let me know if you run into any issues. Thanks!

**Comment by vugardadalov** [comment]
Thanks 👏
